# Here are the settings that are common to all environments
common: &default_settings
  license_key: '94a43b38f1b6e366814a0a19f94f84d46e119a3b'  
  app_name: Resala
  monitor_mode: true
  developer_mode: false
  log_level: info
  ssl: false
  apdex_t: 0.5
  capture_params: false

  transaction_tracer:
    enabled: true    
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500
  error_collector:
    enabled: true
    capture_source: true    
    ignore_errors: ActionController::RoutingError

development:
  <<: *default_settings
  developer_mode: true
  monitor_mode: false
  
test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  monitor_mode: true
  app_name: Resala(Staging)
  
production:
  <<: *default_settings
  monitor_mode: true
  app_name: Resala